if (CMAKE_SYSTEM_NAME MATCHES "Windows")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA OFF)
  set(IS_IOS OFF)
  set(IS_LINUX OFF)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX OFF)
  set(IS_WIN ON)
elseif (CMAKE_SYSTEM_NAME  MATCHES  "Android")
  set(IS_ANDROID ON)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA OFF)
  set(IS_IOS OFF)
  set(IS_LINUX OFF)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)  
elseif (CMAKE_SYSTEM_NAME MATCHES "Darwin" AND NOT CMAKE_SYSTEM_NAME MATCHES "iOS")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA OFF)
  set(IS_IOS OFF)
  set(IS_LINUX OFF)
  set(IS_MAC ON)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)
elseif (CMAKE_SYSTEM_NAME MATCHES "iOS")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA OFF)
  set(IS_IOS ON)
  set(IS_LINUX OFF)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)
elseif (CMAKE_SYSTEM_NAME MATCHES "Linux")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA OFF)
  set(IS_IOS OFF)
  set(IS_LINUX ON)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)  
elseif (CMAKE_SYSTEM_NAME MATCHES  "chromeos")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS ON)
  set(IS_FUCHSIA OFF)
  set(IS_IOS OFF)
  set(IS_LINUX ON)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)
elseif (CMAKE_SYSTEM_NAME MATCHES  "nacl")
  # CMAKE_SYSTEM_NAME MATCHES  "nacl" will be passed by the nacl toolchain definition.
  # It is not set by default or on the command line. We treat is as a
  # Posix variant.
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA OFF)
  set(IS_IOS OFF)
  set(IS_LINUX OFF)
  set(IS_MAC OFF)
  set(IS_NACL ON)
  set(IS_POSIX ON)
  set(IS_WIN OFF)
elseif (CMAKE_SYSTEM_NAME  MATCHES  "fuchsia")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_FUCHSIA ON)
  set(IS_IOS OFF)
  set(IS_LINUX OFF)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)
elseif (CMAKE_SYSTEM_NAME MATCHES  "aix")
  set(IS_ANDROID OFF)
  set(IS_CHROMEOS OFF)
  set(IS_IOS OFF)
  set(IS_LINUX OFF)
  set(IS_MAC OFF)
  set(IS_NACL OFF)
  set(IS_POSIX ON)
  set(IS_WIN OFF)
else()
  message(ERROR "Unsupport platform: ${CMAKE_SYSTEM_NAME}")  
endif()
